In [2]:
from nltk.stem import WordNetLemmatizer 
import nltk
from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\rongy\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [19]:
lemmatizer = WordNetLemmatizer() 
porter = PorterStemmer()
lancaster=LancasterStemmer()
lemmatizer = WordNetLemmatizer() 

print("rocks :", lemmatizer.lemmatize("rocks")) 
print("corpora :", lemmatizer.lemmatize("corpora")) 
  
# a denotes adjective in "pos" 
print("better :", lemmatizer.lemmatize("better", pos ="a")) 

rocks : rock
corpora : corpus
better : good


In [92]:
def get_jaccard_sim(str1, str2): 
    #a = set(map(lancaster.stem, str1.split()))
    a = set(map(lancaster.stem, str1))
    #b = set(map(lancaster.stem, str2.split()))
    b = set(map(lancaster.stem, str2))
    c = a.intersection(b)
    return float(len(c)) / (len(a) + len(b) - len(c))

In [9]:
str1 = 'AI is our friend and it has been friendly'
str2 = 'AI and humans have always been friendly'
get_jaccard_sim(str2, str1)

0.36363636363636365

In [85]:
from collections import Counter
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
def get_cosine_sim(*strs): 
    vectors = [t for t in get_vectors(*strs)]
    return cosine_similarity(vectors)
    
def get_vectors(*strs):
    #strs = [str(list(map(lancaster.stem, t.split()))) for t in strs]
    strs = [str(list(map(lancaster.stem, t))) for t in strs]
    text = [t for t in strs]
    vectorizer = CountVectorizer(text)
    vectorizer.fit(text)
    return vectorizer.transform(text).toarray()

In [39]:
get_cosine_sim(str1, str2)

array([[1.        , 0.56980288],
       [0.56980288, 1.        ]])

In [40]:
get_vectors(str1,str2)

array([[1, 0, 1, 1, 2, 1, 0, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0]], dtype=int64)

In [113]:
porter = PorterStemmer()
lancaster=LancasterStemmer()
#A list of words to be stemmed
word_list = ["friend", "friendship", "friends", "friendships","stabil","destabilize","misunderstanding","railroad","been","is"]
print("{0:20}{1:20}{2:20}".format("Word","Porter Stemmer","lancaster Stemmer"))
for word in word_list:
    print("{0:20}{1:20}{2:20}".format(word,porter.stem(word),lancaster.stem(word)))

Word                Porter Stemmer      lancaster Stemmer   
friend              friend              friend              
friendship          friendship          friend              
friends             friend              friend              
friendships         friendship          friend              
stabil              stabil              stabl               
destabilize         destabil            dest                
misunderstanding    misunderstand       misunderstand       
railroad            railroad            railroad            
been                been                been                
is                  is                  is                  


In [41]:
import pandas as pd
import numpy as np

In [70]:
text1 = pd.read_csv('F:/YI RONG/SIT/SIT/Document/FE800/arxiv sanity preserver/Paper Database/2005 fin+ec papers/csv/0704.0589v1.pdf.txt.csv', encoding = "ISO-8859-1", header = None)
text1 = text1.loc[:,1]
text2 = pd.read_csv('F:/YI RONG/SIT/SIT/Document/FE800/arxiv sanity preserver/Paper Database/2005 fin+ec papers/csv/0704.1225v1.pdf.txt.csv', encoding = "ISO-8859-1", header = None)
text2 = text2.loc[:,1]

In [94]:
get_jaccard_sim(text1, text2)

0.11652078774617068

In [93]:
get_cosine_sim(text1, text2)

array([[1.        , 0.91345606],
       [0.91345606, 1.        ]])